#!/usr/bin/env python3
"""
Check Data Freshness Script

This script monitors the freshness of the various data pipelines that feed into the NFP Predictor.
It checks the most recent modification times of the snapshot generated by the FRED employment pipeline,
exogenous FRED pipeline, NOAA pipeline, Unifier pipeline, and Prosper pipeline. It also checks the 
master snapshots and the trained models.

Usage:
    python scripts/check_data_freshness.py
    python scripts/check_data_freshness.py --alert-days 7
"""

import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime, timedelta
import json
import argparse
import sys

sys.path.append(str(Path(__file__).resolve().parent.parent))

from settings import DATA_PATH, OUTPUT_DIR, TEMP_DIR, setup_logger
from Train.config import MASTER_SNAPSHOTS_DIR, MODEL_SAVE_DIR

logger = setup_logger(__file__, TEMP_DIR)


def get_latest_file_time(directory: Path, pattern: str = "*.parquet") -> datetime:
    """
    Get the modification time of the most recent file in a directory.

    Args:
        directory (Path): Directory to search in.
        pattern (str): File glob pattern to match against (default: "*.parquet").

    Returns:
        datetime: The modification time of the latest file, or None if no files are found.
    """
    files = list(directory.rglob(pattern))
    
    if not files:
        return None
    
    latest = max(files, key=lambda x: x.stat().st_mtime)
    return datetime.fromtimestamp(latest.stat().st_mtime)


def get_latest_snapshot_month(directory: Path) -> pd.Timestamp:
    """
    Get the most recent snapshot month from the filenames in a directory.

    The filenames are expected to follow the YYYY-MM format.

    Args:
        directory (Path): Directory containing snapshot files.

    Returns:
        pd.Timestamp: The latest snapshot month as a pandas Timestamp, or None if no valid files are found.
    """
    files = list(directory.rglob("*.parquet"))
    
    if not files:
        return None
    
    dates = []
    for f in files:
        try:
            date_str = f.stem
            date = pd.to_datetime(date_str + "-01")
            dates.append(date)
        except:
            continue
    
    return max(dates) if dates else None


def check_data_sources() -> dict:
    """
    Check the freshness of all data sources used in the NFP pipeline.
    
    This function verifies the existence and modification time of the snapshot directories 
    for the various data sources. It checks:
    1. FRED Employment Data
    2. FRED Exogenous Data
    3. NOAA Storm Events Data
    4. Unifier Economic Data
    5. Prosper Consumer Survey Data
    6. Master Snapshots
    7. Trained Models
    
    Returns:
        dict: A dictionary containing freshness metrics (existence, last modified time, days old) 
              for each of the monitored data sources.
    """
    checks = {}
    now = datetime.now()
    
    def check_directory(dir_name: str, path: Path) -> None:
        if path.exists():
            mod_time = get_latest_file_time(path)
            checks[dir_name] = {
                'exists': True,
                'last_modified': mod_time.isoformat() if mod_time else None,
                'days_old': (now - mod_time).days if mod_time else None
            }
        else:
            checks[dir_name] = {'exists': False}

    # Check Base Pipeline Data
    check_directory('fred_employment', DATA_PATH / "fred_data")
    check_directory('fred_exogenous', DATA_PATH / "Exogenous_data" / "exogenous_fred_data")
    check_directory('noaa_weighted', DATA_PATH / "Exogenous_data" / "noaa_weighted_snapshots")
    check_directory('unifier', DATA_PATH / "Exogenous_data" / "exogenous_unifier_data")
    check_directory('prosper', DATA_PATH / "Exogenous_data" / "prosper")
    
    # Check master snapshots
    if MASTER_SNAPSHOTS_DIR.exists():
        snap_time = get_latest_file_time(MASTER_SNAPSHOTS_DIR)
        snap_month = get_latest_snapshot_month(MASTER_SNAPSHOTS_DIR)
        checks['master_snapshots'] = {
            'exists': True,
            'last_modified': snap_time.isoformat() if snap_time else None,
            'days_old': (now - snap_time).days if snap_time else None,
            'latest_month': snap_month.strftime('%Y-%m') if snap_month else None
        }
    else:
        checks['master_snapshots'] = {'exists': False}
    
    # Check trained models
    for target_type in ['nsa', 'sa']:
        model_path = MODEL_SAVE_DIR / f"lightgbm_{target_type}_model.txt"
        if model_path.exists():
            model_time = datetime.fromtimestamp(model_path.stat().st_mtime)
            checks[f'model_{target_type}'] = {
                'exists': True,
                'last_modified': model_time.isoformat(),
                'days_old': (now - model_time).days
            }
        else:
            checks[f'model_{target_type}'] = {'exists': False}
    
    return checks


def generate_report(alert_days: int = 7) -> dict:
    """
    Generate data freshness report.
    
    Args:
        alert_days: Days after which to flag as stale
        
    Returns:
        Dictionary with freshness report
    """
    checks = check_data_sources()
    now = datetime.now()
    
    # Determine overall status
    alerts = []
    for source, info in checks.items():
        if not info.get('exists', False):
            alerts.append(f"MISSING: {source}")
        elif info.get('days_old') and info['days_old'] > alert_days:
            alerts.append(f"STALE: {source} ({info['days_old']} days old)")
    
    status = 'OK' if not alerts else 'WARNING'
    
    report = {
        'timestamp': now.isoformat(),
        'status': status,
        'alert_threshold_days': alert_days,
        'sources': checks,
        'alerts': alerts
    }
    
    return report


def print_report(report: dict) -> None:
    """Print formatted freshness report."""
    print(f"\n{'='*60}")
    print("DATA FRESHNESS REPORT")
    print(f"{'='*60}")
    print(f"Timestamp: {report['timestamp']}")
    print(f"Status: {report['status']}")
    print(f"Alert threshold: {report['alert_threshold_days']} days")
    print()
    
    print("Data Sources:")
    for source, info in report['sources'].items():
        if info.get('exists'):
            days = info.get('days_old', '?')
            status = '✓' if days and days <= report['alert_threshold_days'] else '⚠'
            print(f"  {status} {source}: {days} days old")
            if 'latest_month' in info:
                print(f"      Latest: {info['latest_month']}")
        else:
            print(f"  ✗ {source}: NOT FOUND")
    
    if report['alerts']:
        print(f"\nAlerts ({len(report['alerts'])}):")
        for alert in report['alerts']:
            print(f"  ⚠ {alert}")
    else:
        print("\nNo alerts - all data sources are fresh!")
    
    print(f"{'='*60}")


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Check data freshness for NFP Predictor"
    )
    parser.add_argument(
        '--alert-days', type=int, default=7,
        help="Days after which to flag as stale (default: 7)"
    )
    parser.add_argument(
        '--output', type=str, default=None,
        help="Output path for JSON report"
    )
    parser.add_argument(
        '--quiet', action='store_true',
        help="Only output if there are alerts"
    )
    
    args = parser.parse_args()
    
    report = generate_report(alert_days=args.alert_days)
    
    # Print unless quiet and no alerts
    if not (args.quiet and report['status'] == 'OK'):
        print_report(report)
    
    # Save if output path provided
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            json.dump(report, f, indent=2)
        logger.info(f"Saved report to {output_path}")
    
    # Return non-zero if alerts
    return 1 if report['alerts'] else 0


if __name__ == "__main__":
    exit(main())
